# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["bcachefs"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d7bb32dc-4599-499c-913e-73660f0cf3c6";
    fsType = "bcachefs";
    options = ["noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5764-78C1";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d1772975-d75b-4efa-aed1-3cb602761b56";}
    {device = "/dev/disk/by-uuid/9dc3e2ac-b63d-4dda-8b4c-7be566aa349a";}
  ];

  # Mount multiple-device bcachefs.
  systemd.services.mount-data-volume = let
    target = "/mnt/data";
  in {
    description = "mount data volume";
    bindsTo = ["dev-nvme0n1p3.device" "dev-sda1.device" "dev-sdb1.device"];
    after = ["dev-nvme0n1p3.device" "dev-sda1.device" "dev-sdb1.device" "local-fs-pre.target"];
    before = ["umount.target" "local-fs.target"];
    conflicts = ["umount.target"];
    wantedBy = ["local-fs.target"];
    unitConfig = {
      RequiresMountsFor = target;
      DefaultDependencies = false;
    };
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.util-linux}/bin/mount -t bcachefs -o noatime /dev/nvme0n1p3:/dev/sda1:/dev/sdb1 ${target}";
      ExecStop = "${pkgs.util-linux}/umount ${target}";
    };
  };

  # Mount NAS satoshi.
  fileSystems."/mnt/nas-mck-home" = {
    device = "//nas-changping.ybh1998.space/home";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
    in ["${automount_opts},noperm,credentials=${config.sops.secrets.nas-credentials.path}"];
  };

  fileSystems."/mnt/nas-mck-share" = {
    device = "//nas-changping.ybh1998.space/share";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
    in ["${automount_opts},noperm,credentials=${config.sops.secrets.nas-credentials.path}"];
  };

  fileSystems."/mnt/nas-yyp-home" = {
    device = "//nas.ybh1998.space/home";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
    in ["${automount_opts},noperm,credentials=${config.sops.secrets.nas-credentials.path}"];
  };

  fileSystems."/mnt/nas-yyp-share" = {
    device = "//nas.ybh1998.space/share";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
    in ["${automount_opts},noperm,credentials=${config.sops.secrets.nas-credentials.path}"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
