# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  delugia-code = {
    pname = "delugia-code";
    version = "v2111.01.2";
    src = fetchFromGitHub {
      owner = "adam7";
      repo = "delugia-code";
      rev = "v2111.01.2";
      fetchSubmodules = false;
      sha256 = "sha256-A+PzsHxjM7jS5Ec3ot79T2Pn1DmsMc5BbDgOJ5COCA4=";
    };
  };
}
