# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  astronvim = {
    pname = "astronvim";
    version = "v3.37.6";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "AstroNvim";
      rev = "v3.37.6";
      fetchSubmodules = false;
      sha256 = "sha256-LHGH6kAxiBQwy1uA8oSa8cuI+OBQF0b+cTtmLPNbgvs=";
    };
  };
  catppuccin-bat = {
    pname = "catppuccin-bat";
    version = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bat";
      rev = "ba4d16880d63e656acced2b7d4e034e4a93f74b1";
      fetchSubmodules = false;
      sha256 = "sha256-6WVKQErGdaqb++oaXnY3i6/GuH2FhTgK0v4TN4Y0Wbw=";
    };
    date = "2022-11-10";
  };
  catppuccin-bottom = {
    pname = "catppuccin-bottom";
    version = "c0efe9025f62f618a407999d89b04a231ba99c92";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "bottom";
      rev = "c0efe9025f62f618a407999d89b04a231ba99c92";
      fetchSubmodules = false;
      sha256 = "sha256-VaHX2I/Gn82wJWzybpWNqU3dPi3206xItOlt0iF6VVQ=";
    };
    date = "2022-12-30";
  };
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "c6469190f2ecf25f017d6120bf4e050e6b1d17af";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "c6469190f2ecf25f017d6120bf4e050e6b1d17af";
      fetchSubmodules = false;
      sha256 = "sha256-jodJl4f2T9ViNqsY9fk8IV62CrpC5hy7WK3aRpu70Cs=";
    };
    date = "2023-10-07";
  };
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fcitx5";
      rev = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
      fetchSubmodules = false;
      sha256 = "sha256-uFaCbyrEjv4oiKUzLVFzw+UY54/h7wh2cntqeyYwGps=";
    };
    date = "2022-10-05";
  };
  catppuccin-gitui = {
    pname = "catppuccin-gitui";
    version = "3c97c7af7247b1e0f4366a4d8fab650bcce54100";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "gitui";
      rev = "3c97c7af7247b1e0f4366a4d8fab650bcce54100";
      fetchSubmodules = false;
      sha256 = "sha256-m6Tjch6A2ZPZ3/muvb/9sEAQUZfjnWqcwyhNVeqPS2c=";
    };
    date = "2023-06-21";
  };
  catppuccin-starship = {
    pname = "catppuccin-starship";
    version = "5629d2356f62a9f2f8efad3ff37476c19969bd4f";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "starship";
      rev = "5629d2356f62a9f2f8efad3ff37476c19969bd4f";
      fetchSubmodules = false;
      sha256 = "sha256-nsRuxQFKbQkyEI4TXgvAjcroVdG+heKX5Pauq/4Ota0=";
    };
    date = "2023-07-13";
  };
  gpakosz-tmux = {
    pname = "gpakosz-tmux";
    version = "fd1bbb56148101f4b286ddafd98f2ac2dcd69cd8";
    src = fetchFromGitHub {
      owner = "gpakosz";
      repo = ".tmux";
      rev = "fd1bbb56148101f4b286ddafd98f2ac2dcd69cd8";
      fetchSubmodules = false;
      sha256 = "sha256-LkoRWds7PHsteJCDvsBpZ80zvlLtFenLU3CPAxdEHYA=";
    };
    date = "2023-04-15";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "649f4935b8f32d06890b0228f3c448b498af5140";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "649f4935b8f32d06890b0228f3c448b498af5140";
      fetchSubmodules = false;
      sha256 = "sha256-Bb1Kr+KNpAC5BtYME5VSl/Kn0DkljqXqsG4MBWJ2lsU=";
    };
    date = "2023-10-14";
  };
}
