_: {
  # Homebrew casks.
  homebrew.casks = [
    "1password"
    "adobe-creative-cloud"
    "adrive"
    "alt-tab"
    "altserver"
    "arc"
    "baidunetdisk"
    "balenaetcher"
    "bilibili"
    "cyberduck"
    "feishu"
    "firefox"
    "github"
    "handbrake"
    "iina"
    "itsycal"
    "jetbrains-toolbox"
    "jordanbaird-ice"
    "keepingyouawake"
    "keka"
    "kitty"
    "logitech-options"
    "maccy"
    "meetingbar"
    "microsoft-auto-update"
    "microsoft-office"
    "microsoft-remote-desktop"
    "monitorcontrol"
    "mos"
    "motrix"
    "mounty"
    "neteasemusic"
    "orbstack"
    "qfinder-pro"
    "qq"
    "qsync-client"
    "qudedup-extract-tool"
    "raycast"
    "rectangle"
    "sioyek"
    "spotify"
    "squirrel"
    "stats"
    "steam"
    "tailscale"
    "tencent-lemon"
    "tencent-meeting"
    "thunderbird"
    "transmission"
    "visual-studio-code"
    "warp"
    "wechat"
    "wezterm"
    "xpra"
    "xquartz"
    "zed"
    "zotero"
    # "discord"
    # "element"
    # "google-chrome"
  ];
}
