# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clash-meta = {
    pname = "clash-meta";
    version = "v1.18.5";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "v1.18.5";
      fetchSubmodules = false;
      sha256 = "sha256-YNnZ/wlOzmTAD76py4CRlClPi2S1b4PaanCfT/Q426A=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.32";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.32";
      fetchSubmodules = false;
      sha256 = "sha256-g8zZZ/uQeoJQIzpQY3oMUuWMu4/8OnaOLeLvaii+Tmk=";
    };
  };
  oh-my-rime = {
    pname = "oh-my-rime";
    version = "930b768f77f313309c38da37576c956e6f06abbe";
    src = fetchFromGitHub {
      owner = "Mintimate";
      repo = "oh-my-rime";
      rev = "930b768f77f313309c38da37576c956e6f06abbe";
      fetchSubmodules = false;
      sha256 = "sha256-NE0LOTdC2kZTGHi4nFqCUg02BcYGbdOESR3UBHNk+ZY=";
    };
    date = "2024-06-15";
  };
  ollama = {
    pname = "ollama";
    version = "v0.1.44";
    src = fetchFromGitHub {
      owner = "ollama";
      repo = "ollama";
      rev = "v0.1.44";
      fetchSubmodules = false;
      sha256 = "sha256-dnNuJ1a0C2jNEKBbm47QUGbbQwa2vpy1EYYgm9ZS2C4=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "0b59306d619a29cd345e3277aa5cd0b0d5653eda";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "0b59306d619a29cd345e3277aa5cd0b0d5653eda";
      fetchSubmodules = false;
      sha256 = "sha256-dElBA0baKaMN04sSXvMgfey+I60Zq4b+i+KoYzpxZMQ=";
    };
    date = "2024-06-10";
  };
}
