# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clash-meta = {
    pname = "clash-meta";
    version = "v1.18.5";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "v1.18.5";
      fetchSubmodules = false;
      sha256 = "sha256-YNnZ/wlOzmTAD76py4CRlClPi2S1b4PaanCfT/Q426A=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.32";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.32";
      fetchSubmodules = false;
      sha256 = "sha256-g8zZZ/uQeoJQIzpQY3oMUuWMu4/8OnaOLeLvaii+Tmk=";
    };
  };
  oh-my-rime = {
    pname = "oh-my-rime";
    version = "a745d57846af608921bb2806a16bbe0981ac6322";
    src = fetchFromGitHub {
      owner = "Mintimate";
      repo = "oh-my-rime";
      rev = "a745d57846af608921bb2806a16bbe0981ac6322";
      fetchSubmodules = false;
      sha256 = "sha256-JMLCOtHhN8/IkFXrGFKG3VHfTlBkHJT3TXNVj+/YJsI=";
    };
    date = "2024-06-12";
  };
  ollama = {
    pname = "ollama";
    version = "v0.1.43";
    src = fetchFromGitHub {
      owner = "ollama";
      repo = "ollama";
      rev = "v0.1.43";
      fetchSubmodules = false;
      sha256 = "sha256-cIPFKaOzqnJUCj6Sx5OZCyQGp+tRir+QH5Ho5hHQnSc=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "0b59306d619a29cd345e3277aa5cd0b0d5653eda";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "0b59306d619a29cd345e3277aa5cd0b0d5653eda";
      fetchSubmodules = false;
      sha256 = "sha256-dElBA0baKaMN04sSXvMgfey+I60Zq4b+i+KoYzpxZMQ=";
    };
    date = "2024-06-10";
  };
}
