# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clash-meta = {
    pname = "clash-meta";
    version = "v1.18.3";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "v1.18.3";
      fetchSubmodules = false;
      sha256 = "sha256-/fFVUI++OhOer5DrvcXO+R+4whtb5+3Qg3e4+ikJr1Y=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.31";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.31";
      fetchSubmodules = false;
      sha256 = "sha256-A/OE67qAn9RHSCveiRwG5lPYNTMdrbUWVfQOP3XjkdU=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "d3bbbef8f5696a3afc20ab6736d5e0cbe9b69051";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "d3bbbef8f5696a3afc20ab6736d5e0cbe9b69051";
      fetchSubmodules = false;
      sha256 = "sha256-Diz3iRorbkIkq9YC1jBUZxO9TCSNmEP97IU9tGXy0to=";
    };
    date = "2024-04-20";
  };
}
