name: Build nano
on:
  push:
    branches:
      - main
      - update_flake_lock_action
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-macos.yaml
    with:
      hostname: nano
    secrets: inherit
