name: Build satoshi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-macos.yaml
    with:
      hostname: satoshi
    secrets: inherit
