name: Build nix-darwin configuration
on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
jobs:
  build:
    runs-on: macos-latest
    environment: cachix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Use cachix nix cache
        uses: cachix/cachix-action@v15
        with:
          name: nichijou
          extraPullNames: colmena,cuda-maintainers,deadnix,hyprland,nix-community,nixpkgs-wayland,numtide,nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build system configuration
        run: nix build ".#darwinConfigurations.${{ inputs.hostname }}.config.system.build.toplevel"
