name: Build darwin host sakamoto
on:
  push:
    branches:
      - main
    paths:
      - "homes/x86_64-darwin/yousiki@sakamoto/**"
      - "modules/common/**"
      - "modules/home/**"
      - "modules/darwin/**"
      - "secrets/**"
      - "systems/x86_64-darwin/sakamoto/**"
      - ".sops.yaml"
      - "flake.nix"
      - "flake.lock"
  pull_request:
    branches:
      - main
    paths:
      - "homes/x86_64-darwin/yousiki@sakamoto/**"
      - "modules/common/**"
      - "modules/home/**"
      - "modules/darwin/**"
      - "secrets/**"
      - "systems/x86_64-darwin/sakamoto/**"
      - ".sops.yaml"
      - "flake.nix"
      - "flake.lock"
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-macos.yaml
    with:
      hostname: sakamoto
    secrets: inherit
