name: Build hakase
on:
  push:
    branches:
      - main
    paths:
      - "homes/x86_64-linux/yousiki@hakase/**"
      - "modules/common/**"
      - "modules/home/**"
      - "modules/nixos/**"
      - "secrets/**"
      - "systems/x86_64-linux/hakase/**"
      - ".sops.yaml"
      - "flake.nix"
      - "flake.lock"
  pull_request:
    branches:
      - main
    paths:
      - "homes/x86_64-linux/yousiki@hakase/**"
      - "modules/common/**"
      - "modules/home/**"
      - "modules/nixos/**"
      - "secrets/**"
      - "systems/x86_64-linux/hakase/**"
      - ".sops.yaml"
      - "flake.nix"
      - "flake.lock"
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-nixos.yaml
    with:
      hostname: hakase
    secrets: inherit
