name: devshell

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    environment: cachix
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use cachix nix cache
        uses: cachix/cachix-action@master
        with:
          name: nichijou
          extraPullNames: colmena,cuda-maintainers,hyprland,nix-community,nixpkgs-wayland,numtide,nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build devshell
        run: nix develop --command "menu"