name: Build hakase
on:
  push:
    branches:
      - main
      - update_flake_lock_action
  pull_request:
    branches:
      - update_flake_lock_action
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-nixos.yaml
    with:
      hostname: hakase
    secrets: inherit
