name: Check
on:
  push:
    paths:
      - "**/*.nix"
      - ".github/workflows/check.yaml"
      - "flake.*"
      - "nix/**"
  pull_request:
  workflow_dispatch:
jobs:
  skip-check:
    name: Skip check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - name: Skip Check
        uses: fkirc/skip-duplicate-actions@v5
        id: skip-check
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  check:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v10
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Use magic nix cache
        uses: DeterminateSystems/flakehub-cache-action@v2
      - name: Run nix flake check
        run: nix flake check --all-systems
  statix:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    name: Lint nix code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@v10
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Use magic nix cache
        uses: DeterminateSystems/flakehub-cache-action@v2
      - name: Use cachix nix cache
        uses: cachix/cachix-action@v16
        with:
          name: statix
      - name: Run statix
        uses: jocelynthode/statix-action@1.0
  deadnix:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    name: Analyze nix dead code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@v10
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Use magic nix cache
        uses: DeterminateSystems/flakehub-cache-action@v2
      - name: Use cachix nix cache
        uses: cachix/cachix-action@v16
        with:
          name: deadnix
      - name: Run deadnix
        uses: SuperSandro2000/deadnix-action@patch-1
