name: Check
on:
  push:
    branches:
      - main
    paths:
      - "**/*.nix"
      - ".github/workflows/check.yaml"
      - "flake.*"
      - "nix/**"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.nix"
      - ".github/workflows/check.yaml"
      - "flake.*"
      - "nix/**"
  workflow_dispatch:
jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Run nix flake check
        run: nix flake check --all-systems
  statix:
    name: Lint nix code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Use cachix nix cache
        uses: cachix/cachix-action@v16
        with:
          name: statix
      - name: Run statix
        uses: jocelynthode/statix-action@1.0
  deadnix:
    name: Analyze nix dead code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Use cachix nix cache
        uses: cachix/cachix-action@v16
        with:
          name: deadnix
      - name: Run deadnix
        uses: SuperSandro2000/deadnix-action@patch-1
