name: Check nix flake
on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
  pull_request:
    branches:
      - main
    paths:
      - "**.nix"
  workflow_dispatch:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run nix flake check
        run: nix flake check --all-systems
