name: Dead code analysis
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Use cachix nix cache
        uses: cachix/cachix-action@v15
        with:
          name: deadnix
      - name: Run deadnix
        uses: astro/deadnix-action@v1
        with:
          commit_message: "chore: remove dead code"
