name: "Check and build flake"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --all-systems
      
  flake-checker:
    name: flake-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/flake-checker-action@main