name: Code linting
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  statix:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check flake.lock file
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use cachix nix cache
        uses: cachix/cachix-action@master
        with:
          name: statix
      - name: Run statix
        uses: jocelynthode/statix-action@master
