name: Linting
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  statix:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
