name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - name: Use cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --all-systems
      
  flake-checker:
    name: flake-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main