name: Update flake inputs
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-flake-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" 
          pr-labels: |                  
            dependencies
            automated
            merge-queue
