name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Use cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
