name: Update packages

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  update-packages:
    name: Update packages
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Setup cachix cache
        uses: cachix/cachix-action@v16
        with:
          name: nichijou
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: catppuccin,colmena,deadnix,hyprland,nix-community,nixpkgs-wayland,numtide,zed
      - name: Get current platform
        id: get-platform
        run: echo "platform=$(nix eval --raw --impure --expr 'builtins.currentSystem')" >> $GITHUB_ENV
      - name: Check if branch exists
        id: check-branch
        run: |
          branch_name="update-packages-${{ steps.get-platform.outputs.platform }}"
          if git ls-remote --heads origin $branch_name | grep -q $branch_name; then
            echo "branch-exists=true" >> $GITHUB_OUTPUT
            echo "Branch $branch_name already exists. Skipping workflow."
          else
            echo "branch-exists=false" >> $GITHUB_OUTPUT
            echo "Branch $branch_name does not exist. Proceeding with workflow."
          fi
      - name: Update packages
        if: steps.check-branch.outputs.branch-exists == 'false'
        run: nix run .#update-packages
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create-pull-request
        if: steps.check-branch.outputs.branch-exists == 'false'
        with:
          token: ${{ secrets.ACTIONS_PR_TOKEN }}
          commit-message: "chore: update packages"
          title: "Automated update of packages"
          body: |
            This Pull Request updates packages to the latest versions.
          branch: update-packages-darwin
          labels: |
            automated
            dependencies
            merge-queue
      - name: Enable auto-merge for Pull Request
        if: steps.check-branch.outputs.branch-exists == 'false' && steps.create-pull-request.outputs.pull-request-operation == 'created'
        run: gh pr merge --merge --auto --delete-branch $PR_NUMBER
        env:
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
          GH_TOKEN: ${{ secrets.ACTIONS_PR_TOKEN }}
