name: Update packages

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  update-packages:
    name: Update packages
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix and flakes
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Setup cachix cache
        uses: cachix/cachix-action@v16
        with:
          name: nichijou
          extraPullNames: nix-community,numtide
      - name: Get current platform
        id: get-platform
        run: |
          platform=$(nix eval --raw --impure --expr 'builtins.currentSystem')
          echo "platform=$platform" >> $GITHUB_OUTPUT
      - name: Update packages
        run: nix run .#update-packages
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create-pull-request
        with:
          token: ${{ secrets.ACTIONS_PR_TOKEN }}
          commit-message: "chore: update packages"
          title: "Automated update of packages"
          body: |
            This Pull Request updates packages to the latest versions.
          branch: update-packages-${{ steps.get-platform.outputs.platform }}
          labels: |
            automated
            dependencies
            merge-queue
      - name: Enable auto-merge for Pull Request
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        run: gh pr merge --squash --auto $PR_NUMBER
        env:
          PR_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
          GH_TOKEN: ${{ secrets.ACTIONS_PR_TOKEN }}
